#!/usr/bin/env node

var s3 = require('s3');

var AWS_BUCKET = process.env.AWS_BUCKET || 'portal.fixt.co';
var AWS_REGION = process.env.AWS_REGION || 'us-west-1';
var AWS_ACCESS_KEY = process.env.AWS_ACCESS_KEY;
var AWS_SECRET_KEY = process.env.AWS_SECRET_KEY;

var s3_sync = function () {
  var client = s3.createClient({
    s3Options: {
      accessKeyId: AWS_ACCESS_KEY,
      secretAccessKey: AWS_SECRET_KEY,
      region: AWS_REGION
    },
  });

  var params = {
    localDir: "dist",

    s3Params: {
      Bucket: AWS_BUCKET,
      Prefix: "",
    }
  }

  var uploader = client.uploadDir(params);

  uploader.on('error', function(err) {
    console.error("unable to sync:", err.stack);
    process.exit(1);
  });

  uploader.on('progress', function() {
    console.log("progress", uploader.progressAmount, uploader.progressTotal);
  });

  uploader.on('end', function() {
    console.log("done uploading");
  });
}


if (AWS_ACCESS_KEY && AWS_SECRET_KEY) {
  s3_sync();
} else {
  console.error("ERROR: You are missing environment variables AWS_ACCESS_KEY or AWS_SECRET_KEY");
}
